name: Deploy to Server

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 2-6'  # Runs at 3:00 AM UTC from Tuesday to Saturday

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy code
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/myenv/git-training/src/ && git pull origin ${{ secrets.MAIN_BRANCH }}"

      - name: Run application_test.py
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/myenv/git-training/src/ && python3 application_test.py"

      - name: Run date_minus.py
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/myenv/git-training/src/ && python3 date_minus.py"

      - name: Run imos_request.py
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/myenv/git-training/src/ && python3 imos_requests.py"

      - name: Send success email
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Actions Workflow Succeeded IMOS
          body: |
            The GitHub Actions workflow has completed successfully.
            The data have imported to IMOS platform successfully.
          to: epp@cmm.gr, epoulea@outlook.com
          from: github-actions@example.com
